fastlane_version '2.157'
default_platform :ios

platform :ios do
  desc 'Builds project and executes unit tests'
  lane :unit_test do
    scan(
      workspace: "TodoList.xcodeproj/project.xcworkspace",
      scheme: "TodoList",
      device: "iPhone 14",
      clean: true,
      code_coverage: true,
      derived_data_path: "Build/",
      prelaunch_simulator: true,
      xcargs: "-parallelizeTargets"
    )
  end
end
