name: iOS Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Build app
        run: xcodebuild -project TodoList.xcodeproj -scheme TodoList -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' build

      - name: Run Tests
        run: xcodebuild test -project TodoList.xcodeproj -scheme TodoList -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0'
